/* tslint:disable */
/* eslint-disable */
import { GraphQLResolveInfo, GraphQLScalarType } from 'graphql';
/**
 * This file is auto-generated by graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */
 

/*******************************
 *                             *
 *          TYPE DEFS          *
 *                             *
 *******************************/
export type GQLAWSDate = string;

export type GQLAWSTime = string;

export type GQLAWSDateTime = string;

export type GQLAWSTimestamp = number;

export type GQLAWSEmail = string;

export type GQLAWSJSON = string;

export type GQLAWSURL = string;

export type GQLAWSPhone = string;

export type GQLAWSIPAddress = string;

export interface GQLQuiz {
  topic: string;
  title: string;
  quizCode: string;
  questions: Array<GQLQuizQuestion>;
}

export interface GQLQuizQuestion {
  questionText: string;
  options: Array<GQLQuizQuestionOption>;
}

export interface GQLQuizQuestionOption {
  optionText: string;
  isCorrect: boolean;
}

export interface GQLQuizListResult {
  items: Array<GQLQuiz>;
  lastEvaluatedKey?: string;
}

export interface GQLQuizInput {
  topic: string;
  title: string;
  questions: Array<GQLQuizInputQuestion>;
}

export interface GQLQuizInputQuestion {
  questionText: string;
  options: Array<GQLQuizInputQuestionOption>;
}

export interface GQLQuizInputQuestionOption {
  optionText: string;
  isCorrect: boolean;
}

export interface GQLQuery {
  quizList: GQLQuizListResult;
  topicList: Array<string>;
  scoreList: GQLScoreListResult;
}

export interface GQLMutation {
  
  /**
   * 
   * @deprecated
   */
  addQuiz: GQLQuiz;
  populateQuizData: number;
  addScore: GQLScore;
}

export interface GQLDDBPagination {
  limit: number;
  exclusiveStartKey?: string;
}

export interface GQLKeyValue {
  string?: string;
  float?: number;
  int?: number;
}

export interface GQLKeyConditionExpression {
  pk: GQLKeyValue;
  sk?: GQLSKConditionExpression;
}

export interface GQLSKConditionExpression {
  eq?: GQLKeyValue;
  lt?: GQLKeyValue;
  lte?: GQLKeyValue;
  gt?: GQLKeyValue;
  gte?: GQLKeyValue;
  beginsWith?: GQLKeyValue;
  between?: GQLSKBetweenConditionExpression;
}

export interface GQLSKBetweenConditionExpression {
  from: GQLKeyValue;
  to: GQLKeyValue;
}

export interface GQLScore {
  username: string;
  userNickname: string;
  createdAt: GQLAWSDateTime;
  quizCode: string;
  title: string;
  topic: string;
  nQuestions: number;
  nCorrect: number;
  percentage: number;
}

export interface GQLScoreListResult {
  items: Array<GQLScore>;
  lastEvaluatedKey?: string;
}

export interface GQLScoreInput {
  quizCode: string;
  title: string;
  topic: string;
  nQuestions: number;
  nCorrect: number;
}

export interface GQLScoreIndexConfig {
  quizCode_createdAt?: boolean;
  quizCode_percentage?: boolean;
  user_createdAt?: boolean;
  user_quizCode?: boolean;
}

/*********************************
 *                               *
 *         TYPE RESOLVERS        *
 *                               *
 *********************************/
/**
 * This interface define the shape of your resolver
 * Note that this type is designed to be compatible with graphql-tools resolvers
 * However, you can still use other generated interfaces to make your resolver type-safed
 */
export interface GQLResolver {
  AWSDate?: GraphQLScalarType;
  AWSTime?: GraphQLScalarType;
  AWSDateTime?: GraphQLScalarType;
  AWSTimestamp?: GraphQLScalarType;
  AWSEmail?: GraphQLScalarType;
  AWSJSON?: GraphQLScalarType;
  AWSURL?: GraphQLScalarType;
  AWSPhone?: GraphQLScalarType;
  AWSIPAddress?: GraphQLScalarType;
  Quiz?: GQLQuizTypeResolver;
  QuizQuestion?: GQLQuizQuestionTypeResolver;
  QuizQuestionOption?: GQLQuizQuestionOptionTypeResolver;
  QuizListResult?: GQLQuizListResultTypeResolver;
  Query?: GQLQueryTypeResolver;
  Mutation?: GQLMutationTypeResolver;
  Score?: GQLScoreTypeResolver;
  ScoreListResult?: GQLScoreListResultTypeResolver;
}
export interface GQLQuizTypeResolver<TParent = any> {
  topic?: QuizToTopicResolver<TParent>;
  title?: QuizToTitleResolver<TParent>;
  quizCode?: QuizToQuizCodeResolver<TParent>;
  questions?: QuizToQuestionsResolver<TParent>;
}

export interface QuizToTopicResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QuizToTitleResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QuizToQuizCodeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QuizToQuestionsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLQuizQuestionTypeResolver<TParent = any> {
  questionText?: QuizQuestionToQuestionTextResolver<TParent>;
  options?: QuizQuestionToOptionsResolver<TParent>;
}

export interface QuizQuestionToQuestionTextResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QuizQuestionToOptionsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLQuizQuestionOptionTypeResolver<TParent = any> {
  optionText?: QuizQuestionOptionToOptionTextResolver<TParent>;
  isCorrect?: QuizQuestionOptionToIsCorrectResolver<TParent>;
}

export interface QuizQuestionOptionToOptionTextResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QuizQuestionOptionToIsCorrectResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLQuizListResultTypeResolver<TParent = any> {
  items?: QuizListResultToItemsResolver<TParent>;
  lastEvaluatedKey?: QuizListResultToLastEvaluatedKeyResolver<TParent>;
}

export interface QuizListResultToItemsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QuizListResultToLastEvaluatedKeyResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLQueryTypeResolver<TParent = any> {
  quizList?: QueryToQuizListResolver<TParent>;
  topicList?: QueryToTopicListResolver<TParent>;
  scoreList?: QueryToScoreListResolver<TParent>;
}

export interface QueryToQuizListArgs {
  cond: GQLKeyConditionExpression;
  pagination?: GQLDDBPagination;
}
export interface QueryToQuizListResolver<TParent = any, TResult = any> {
  (parent: TParent, args: QueryToQuizListArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QueryToTopicListResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QueryToScoreListArgs {
  cond: GQLKeyConditionExpression;
  indexConfig: GQLScoreIndexConfig;
  pagination: GQLDDBPagination;
}
export interface QueryToScoreListResolver<TParent = any, TResult = any> {
  (parent: TParent, args: QueryToScoreListArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLMutationTypeResolver<TParent = any> {
  addQuiz?: MutationToAddQuizResolver<TParent>;
  populateQuizData?: MutationToPopulateQuizDataResolver<TParent>;
  addScore?: MutationToAddScoreResolver<TParent>;
}

export interface MutationToAddQuizArgs {
  input: GQLQuizInput;
}
export interface MutationToAddQuizResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToAddQuizArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToPopulateQuizDataResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToAddScoreArgs {
  input: GQLScoreInput;
}
export interface MutationToAddScoreResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToAddScoreArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLScoreTypeResolver<TParent = any> {
  username?: ScoreToUsernameResolver<TParent>;
  userNickname?: ScoreToUserNicknameResolver<TParent>;
  createdAt?: ScoreToCreatedAtResolver<TParent>;
  quizCode?: ScoreToQuizCodeResolver<TParent>;
  title?: ScoreToTitleResolver<TParent>;
  topic?: ScoreToTopicResolver<TParent>;
  nQuestions?: ScoreToNQuestionsResolver<TParent>;
  nCorrect?: ScoreToNCorrectResolver<TParent>;
  percentage?: ScoreToPercentageResolver<TParent>;
}

export interface ScoreToUsernameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ScoreToUserNicknameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ScoreToCreatedAtResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ScoreToQuizCodeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ScoreToTitleResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ScoreToTopicResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ScoreToNQuestionsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ScoreToNCorrectResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ScoreToPercentageResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLScoreListResultTypeResolver<TParent = any> {
  items?: ScoreListResultToItemsResolver<TParent>;
  lastEvaluatedKey?: ScoreListResultToLastEvaluatedKeyResolver<TParent>;
}

export interface ScoreListResultToItemsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ScoreListResultToLastEvaluatedKeyResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}
